### PR TITLE
YLP-532 Reset password demand can be used several times

### PR DESCRIPTION
**Pull request by CedricPerotto**

### CODE REVIEW

**Review by ydrisR — DISMISSED** [review]
LGTM with a few comments/questions:
1. tests fail ona seagull call (config issue due to the changes?)
2. is it possible to unit test the bug that was corrected? Or should we create a system test?
3. will need to change the k8S configuration for seagull host

**Review by ydrisR — CHANGES_REQUESTED** [review]
Need to update tests to use the new seagull mock. This mock requieres expectations.

**Comment by Nas84** [comment]
what do you think if we decrease also the validity time period (same as the Patient)? 
```Go
	Timeouts TypeDurations = TypeDurations{
		...
		TypePasswordReset:        7 * 24 * time.Hour,
		...
		TypePatientPasswordReset: 1 * time.Hour,
	}
```

**Comment by franck-fourel** [comment]
> what do you think if we decrease also the validity time period (same as the Patient)?
> 
> ```go
> 	Timeouts TypeDurations = TypeDurations{
> 		...
> 		TypePasswordReset:        7 * 24 * time.Hour,
> 		...
> 		TypePatientPasswordReset: 1 * time.Hour,
> 	}
> ```

I would really prefer to make this change in a different PR. 
Let's discuss that with Marine & Regis

**Comment by franck-fourel** [comment]
> Need to update tests to use the new seagull mock. This mock requieres expectations.

done in d8a60bab98df22e00b0f44c441cd5b2f5a08ddf2

**Review by ydrisR — APPROVED** [review]
LGTM

**Pull request merged**
