### PR TITLE
PT-1315 Generate and Send an email with a new handset PIN code

### PR DESCRIPTION
**Pull request by BigFab**
This PR updates Hydrophone so there is a new route for generating a patient pin reset unique code using the logic of TOTP (time based one time password)
It is using a new functionality of go-common that is wrapping a call to _portal-api_ to get the IMEI of the connected patient (using his token)
I added Unit Tests separate for TOTP functions and for the new route

__We will need to create Integration Tests in the YourLoops stack.__

__Note:__ I also created a PR in _platforms_utils_ for the Java code that can potentially be leveraged by Devdroid

### CODE REVIEW

**Review by ydrisR — CHANGES_REQUESTED** [review]
Good work 👍 
Tested on a local env and it works well :)
A few comments:
* Update the changelog
* Update the sample env files with portal config.
* Underscore looks a bit strange as a word delimiter within a url. hyphens seems more widely used... `send/pin-reset/{{loginEmail}}`
* Perhaps (just an idea...) store the OTP code in the confirm DB? Or log in hydrophone logs. It may help for troubleshooting purpose.
* Need a fake OTP value to preview the new email on the `generateEmail` method.
```
content := map[string]interface{}{
		"Key":          "123456789",
		"Email":        "john@diabeloop.com",
		"FullName":     "John Doe",
		"CareteamName": "John Doe",
		"WebPath":      "login",
		"OTP":          "165236984",
}
```

**Comment by BigFab** [comment]
I am implementing all the review comments, thanks. For the OTP to be recorded in DB, this is done already, using the confirmation context, which (for some reason I ignore) is binary encoded in the 'context' field of the confirm document. I used the `NewConfirmationWithContext` method that is used everywhere else in the code. Not sure, this was the best way to do though

**Comment by BigFab** [comment]
I am now waiting for the other PR to pass (https://github.com/mdblp/hydrophone/pull/89) before I push my changes, including a version bump

**Review by ydrisR — APPROVED** [review]
LGTM

**Pull request merged**
